{{- if .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.secrets.namespace }}
spec:
  provider: {{ .Values.secrets.provider }}
  parameters:
    region: {{ .Values.secrets.region }}
    objects: |
{{ toYaml .Values.secrets.objects | indent 6 }}
  secretObjects:
{{- range .Values.secrets.secretObjects }}
    - secretName: {{ .secretName }}
      type: {{ .type }}
      data:
{{- range .data }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
{{- end }}
{{- end }}
{{- end }}
