# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: django-db-secret
# spec:
#   provider: aws
#   parameters:
#     region: us-east-1
#     objects: |
#       - objectName: "django-db-secret"
#         objectType: "secretsmanager"

#         jmesPath:
#           - path: DB_USER
#             objectAlias: DB_USER
#           - path: DB_PASS
#             objectAlias: DB_PASS
#           - path: DB_NAME
#             objectAlias: DB_MANE
#           - path: SECRET_KEY
#             objectAlias: SECRET_KEY



# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: django-db-secret
#   namespace: default
# spec:
#   provider: aws
#   parameters:
#     region: us-east-1
#     objects: |
#       - objectName: "arn:aws:secretsmanager:us-east-1:837318114635:secret:django-db-secret"
#         objectType: "secretsmanager"
#         jmesPath:
#           - path: DB_USER
#             objectAlias: DB_USER
#           - path: DB_PASS
#             objectAlias: DB_PASS
#           - path: DB_NAME
#             objectAlias: DB_MANE
#           - path: SECRET_KEY
#             objectAlias: SECRET_KEY


apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: django-db-secret
  namespace: default
spec:
  provider: aws
  parameters:
    region: us-east-1
    # usePodIdentity: "true"
    objects: |
      - objectName: "django-db-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: DB_USER
            objectAlias: DB_USER
          - path: DB_PASS
            objectAlias: DB_PASS
          - path: DB_NAME
            objectAlias: DB_NAME
          - path: SECRET_KEY
            objectAlias: SECRET_KEY
    
  secretObjects:
    - secretName: django-aws-secret
      type: Opaque
      data:
        - objectName: DB_USER
          key: DB_USER
        - objectName: DB_PASS
          key: DB_PASS
        - objectName: DB_NAME
          key: DB_NAME
        - objectName: SECRET_KEY
          key: SECRET_KEY

